import jsPDF from "jspdf";

interface RecipeForPdf {
  title: string;
  description?: string;
  tag?: string;
  servingSize: number;
  ingredients: string[];
  instructions: string[];
  substitutes?: Record<string, string[]>;
  healthRating?: number;
  healthRatingReason?: string;
  nutritionalValues: {
    calories: string;
    protein: string;
    carbs: string;
    fat: string;
    fiber: string;
  };
  costBreakdown?: { item: string; cost: number }[];
  totalCost?: number;
}

// Brand colors (orange-centric, matches design system roughly)
const PRIMARY: [number, number, number] = [234, 88, 12]; // orange-600
const ACCENT: [number, number, number] = [249, 115, 22]; // orange-500
const TEXT: [number, number, number] = [30, 30, 30];
const MUTED: [number, number, number] = [110, 110, 110];
const LIGHT_BG: [number, number, number] = [255, 247, 237]; // orange-50
const BORDER: [number, number, number] = [253, 186, 116]; // orange-300

export function exportRecipeToPdf(
  recipe: RecipeForPdf,
  scaledIngredients: string[],
  scaledNutrition: Record<string, string>,
  scaledCostBreakdown: { item: string; cost: number }[],
  scaledTotalCost: number,
  servings: number
) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 40;
  const contentWidth = pageWidth - margin * 2;
  let y = 0;

  const ensureSpace = (needed: number) => {
    if (y + needed > pageHeight - 50) {
      addFooter();
      doc.addPage();
      y = margin;
    }
  };

  const addFooter = () => {
    const pageNum = doc.getCurrentPageInfo().pageNumber;
    doc.setFontSize(9);
    doc.setTextColor(...MUTED);
    doc.setFont("helvetica", "normal");
    doc.text(
      "Generated by AI Recipe Generator",
      margin,
      pageHeight - 25
    );
    doc.text(`Page ${pageNum}`, pageWidth - margin, pageHeight - 25, { align: "right" });
  };

  // ===== Header band =====
  doc.setFillColor(...PRIMARY);
  doc.rect(0, 0, pageWidth, 90, "F");
  doc.setFillColor(...ACCENT);
  doc.rect(0, 80, pageWidth, 10, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  const titleLines = doc.splitTextToSize(recipe.title, contentWidth);
  doc.text(titleLines, margin, 45);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  if (recipe.description) {
    doc.text(recipe.description, margin, 70, { maxWidth: contentWidth });
  }

  y = 115;

  // ===== Meta row =====
  doc.setTextColor(...TEXT);
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text(`Servings: `, margin, y);
  doc.setFont("helvetica", "normal");
  doc.text(`${servings}`, margin + 50, y);

  if (recipe.tag) {
    doc.setFont("helvetica", "bold");
    doc.text(`Category: `, margin + 130, y);
    doc.setFont("helvetica", "normal");
    doc.text(recipe.tag, margin + 185, y);
  }

  if (recipe.healthRating) {
    doc.setFont("helvetica", "bold");
    doc.text(`Health Rating: `, margin + 280, y);
    doc.setFont("helvetica", "normal");
    doc.text(`${recipe.healthRating}/5`, margin + 360, y);
  }
  y += 22;

  // ===== Section helper =====
  const sectionHeader = (label: string) => {
    ensureSpace(35);
    doc.setFillColor(...LIGHT_BG);
    doc.setDrawColor(...BORDER);
    doc.roundedRect(margin, y, contentWidth, 26, 4, 4, "FD");
    doc.setTextColor(...PRIMARY);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.text(label, margin + 12, y + 18);
    y += 36;
    doc.setTextColor(...TEXT);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10.5);
  };

  // ===== Nutritional Values =====
  sectionHeader("Nutritional Values");
  const nutKeys = ["calories", "protein", "carbs", "fat", "fiber"] as const;
  const cellW = contentWidth / 5;
  ensureSpace(56);
  nutKeys.forEach((k, i) => {
    const x = margin + i * cellW;
    doc.setDrawColor(...BORDER);
    doc.setFillColor(255, 255, 255);
    doc.roundedRect(x + 2, y, cellW - 4, 50, 4, 4, "FD");
    doc.setTextColor(...MUTED);
    doc.setFontSize(9);
    doc.text(k.toUpperCase(), x + cellW / 2, y + 16, { align: "center" });
    doc.setTextColor(...PRIMARY);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.text(scaledNutrition[k] || "—", x + cellW / 2, y + 36, { align: "center" });
    doc.setFont("helvetica", "normal");
  });
  y += 64;

  // ===== Ingredients =====
  sectionHeader("Ingredients");
  scaledIngredients.forEach((ing, idx) => {
    const lines = doc.splitTextToSize(`${idx + 1}. ${ing}`, contentWidth - 20);
    ensureSpace(lines.length * 14 + 4);
    doc.setTextColor(...TEXT);
    doc.text(lines, margin + 12, y);
    y += lines.length * 14 + 2;

    const subs = recipe.substitutes?.[ing] || recipe.substitutes?.[recipe.ingredients[idx]];
    if (subs && subs.length) {
      const subText = `   Alt: ${subs.join(", ")}`;
      const subLines = doc.splitTextToSize(subText, contentWidth - 30);
      ensureSpace(subLines.length * 12 + 2);
      doc.setTextColor(...MUTED);
      doc.setFontSize(9);
      doc.text(subLines, margin + 18, y);
      y += subLines.length * 12 + 2;
      doc.setFontSize(10.5);
    }
  });
  y += 8;

  // ===== Cost Breakdown =====
  if (scaledCostBreakdown && scaledCostBreakdown.length > 0) {
    sectionHeader("Cost Breakdown (INR)");
    // Table header
    ensureSpace(24);
    doc.setFillColor(...PRIMARY);
    doc.rect(margin, y, contentWidth, 22, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10.5);
    doc.text("Ingredient", margin + 10, y + 15);
    doc.text("Cost", pageWidth - margin - 10, y + 15, { align: "right" });
    y += 22;

    doc.setFont("helvetica", "normal");
    doc.setTextColor(...TEXT);
    scaledCostBreakdown.forEach((c, idx) => {
      const itemLines = doc.splitTextToSize(c.item, contentWidth - 80);
      const rowH = Math.max(20, itemLines.length * 13 + 6);
      ensureSpace(rowH);
      if (idx % 2 === 0) {
        doc.setFillColor(252, 252, 252);
        doc.rect(margin, y, contentWidth, rowH, "F");
      }
      doc.setDrawColor(230, 230, 230);
      doc.line(margin, y + rowH, margin + contentWidth, y + rowH);
      doc.setTextColor(...TEXT);
      doc.text(itemLines, margin + 10, y + 14);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...PRIMARY);
      doc.text(`Rs. ${c.cost}`, pageWidth - margin - 10, y + 14, { align: "right" });
      doc.setFont("helvetica", "normal");
      y += rowH;
    });

    // Total row
    ensureSpace(28);
    doc.setFillColor(...LIGHT_BG);
    doc.setDrawColor(...BORDER);
    doc.roundedRect(margin, y, contentWidth, 26, 4, 4, "FD");
    doc.setTextColor(...TEXT);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.text("Total Estimated Cost", margin + 10, y + 17);
    doc.setTextColor(...PRIMARY);
    doc.text(`Rs. ${scaledTotalCost}`, pageWidth - margin - 10, y + 17, { align: "right" });
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10.5);
    y += 36;
  }

  // ===== Instructions =====
  sectionHeader("Instructions");
  recipe.instructions.forEach((step, idx) => {
    const lines = doc.splitTextToSize(step, contentWidth - 36);
    const blockH = lines.length * 14 + 8;
    ensureSpace(blockH);

    // Step number badge
    doc.setFillColor(...PRIMARY);
    doc.circle(margin + 12, y + 6, 9, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.text(`${idx + 1}`, margin + 12, y + 9, { align: "center" });

    doc.setTextColor(...TEXT);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10.5);
    doc.text(lines, margin + 30, y + 10);
    y += blockH;
  });

  // Health rating reason
  if (recipe.healthRatingReason) {
    ensureSpace(40);
    y += 6;
    doc.setFillColor(...LIGHT_BG);
    doc.setDrawColor(...BORDER);
    const reasonLines = doc.splitTextToSize(`Health note: ${recipe.healthRatingReason}`, contentWidth - 20);
    const h = reasonLines.length * 12 + 16;
    doc.roundedRect(margin, y, contentWidth, h, 4, 4, "FD");
    doc.setTextColor(...TEXT);
    doc.setFontSize(10);
    doc.text(reasonLines, margin + 10, y + 14);
    y += h;
  }

  addFooter();
  doc.save(`${recipe.title.replace(/[^a-z0-9]+/gi, "_")}_recipe.pdf`);
}
